exec-once=swaybg -i /home/sierra/.config/wallpaper/jr.png
exec-once=wlr-randr --output DP-1 --mode 1920x1080@143.994995
env=DISPLAY,:2
exec-once=xwayland-satellite :2
exec-once=sleep 1 && xrdb -display :2 -merge ~/.Xresources && st
